### ISSUE TITLE
ios Label is not wrapping in CarouselView

### ISSUE THREAD

**Issue by eyeveye** [AndreiMisiukevich/CardView.MAUI#17]
Label inside CarouselView is not wrapping. Problem only exist in iOS.

Tried to change to Maui.Controls.CarouselView, no problem.

**Comment by vikern22** [comment]
I experience the same issue. (dotnet 8)

**Comment by AndreiMisiukevich** [comment]
Hi folks
I am sure it is related to https://github.com/AndreiMisiukevich/CardView.MAUI/issues/16

But I don't know how to fix that.
Feel free to submit a PR and I will be happy to review and merge it asap

**Comment by AndreiMisiukevich** [comment]
Also, try to wrap the label with something e.g. StackLayout / ContentView
Sorry folks, I don't have much time for this project now

**Comment by vikern22** [comment]
Still does not work for me on 0.0.6

**Comment by AndreiMisiukevich** [comment]
@vikern22 does wrapping the label with content view solves the problem?

**Comment by vikern22** [comment]
@AndreiMisiukevich Can't see any difference on either platform🤷‍♂️

**Comment by DashTheDev** [comment]
@eyeveye @vikern22 Would either of you be able to provide a reproducible project with the label wrapping issue? I had a bit of a play and couldn't reproduce it precisely.

I was having label wrapping issues in a CarouselView on iOS too, but that was the result of a dumb moment from me. In my scenario, I had a parent grid that had a fixed row height, and the text would wrap on Android but not iOS. Increasing the row height or setting to auto fixed it on both which makes sense, since iOS text size renders differently to Android text size.

**Comment by AndreiMisiukevich** [comment]
Thanks @DashTheDev !
BTW a new version is about to be released!

As for the issue, please try latest version on .NET 8
