### ISSUE TITLE
DelayedView (from Sharpnado) doesn't work with CarouselView

### ISSUE THREAD

**Issue by dima059** [AndreiMisiukevich/CardView.MAUI#30]
**Describe the bug**
I am trying to display Sharpnado DelayedViews (from the [Sharpnado](https://github.com/roubachof/Sharpnado.Tabs)) with the CarouselView (as the creator of Sharpnado advised [here](https://github.com/roubachof/Sharpnado.Tabs/issues/27#issuecomment-1449664956)). But I always see activity indicator - view never loads.

P.S.: **I don't know for sure if problem is on Sharpnado side or CardView (or even mine).**

**To Reproduce**
1. Create CarouselView with some DelayedViews
```
<cards:CarouselView>
	<cards:CarouselView.ItemsSource>
		<x:Array Type="{x:Type tabs:ALazyView}"> //I also tried <x:Array Type="{x:Type View}">
			<tabs:DelayedView x:TypeArguments="views:MainPage" UseActivityIndicator="True" />
			<tabs:DelayedView x:TypeArguments="views:MainPage" UseActivityIndicator="True" />
			<tabs:DelayedView x:TypeArguments="views:MainPage" UseActivityIndicator="True" />
		</x:Array>
	</cards:CarouselView.ItemsSource>
</cards:CarouselView>
```
2. Run
3. See that all tabs are always showing an activity indicator.

**Screenshots**
![5264780326461371988](https://github.com/user-attachments/assets/55829d07-d550-4898-b4e0-d0ea106b9010)

But if I remove DelayedViews everything works:
```
<cards:CarouselView>
	<cards:CarouselView.ItemsSource>
		<x:Array Type="{x:Type View}">
			<views:MainPage/>
			<views:MainPage/>
			<views:MainPage/>
		</x:Array>
	</cards:CarouselView.ItemsSource>
</cards:CarouselView>
```

Maybe you can help me. I'll be very grateful!

**Comment by DashTheDev** [comment]
Hey! So, this isn't really a bug or issue per say as the two libraries have no way of knowing how the other works without either taking a dependency on the other.

The issue here is that [Sharpnado](https://github.com/roubachof/Sharpnado.Tabs/tree/main)'s [`DelayedView`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/DelayedView.cs) needs to be loaded explicitly via the [`LoadView`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/LazyView.cs#L15C14-L15C22) method on its base interface. This is usually done by [Sharpnado](https://github.com/roubachof/Sharpnado.Tabs/tree/main) in the [`ViewSwitcher`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/ViewSwitcher.cs#L187), but since in this instance you're using the [`CarouselView`](https://github.com/AndreiMisiukevich/CardView.MAUI/blob/main/PanCardView/Common/CarouselView.cs) the [`LoadView`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/LazyView.cs#L15C14-L15C22) method is never called on your [`DelayedViews`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/DelayedView.cs).

Ultimately that is functionality that will never exist between [CardView.MAUI](https://github.com/AndreiMisiukevich/CardView.MAUI) and [Sharpnado](https://github.com/roubachof/Sharpnado.Tab) as like I mentioned earlier, one would have the take a dependency on the other.

**However!** I did test in a sample app and managed to get a [`CarouselView`](https://github.com/AndreiMisiukevich/CardView.MAUI/blob/main/PanCardView/Common/CarouselView.cs) with [`DelayedViews`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/DelayedView.cs) working. You just need to make sure that each [`DelayedView`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/DelayedView.cs) has its [`LoadView`](https://github.com/roubachof/Sharpnado.Tabs/blob/main/Tabs/Tabs/LazyView.cs#L15C14-L15C22) method called when the view is selected in the Carousel. There'd be a million different ways to do this based on the developer but see the code-behind example I created below.

```C#
public CarouselSampleSharpnadoView()
{
    InitializeComponent();

    MyCarousel.PropertyChanged += OnCarouselPropertyChanged;
    MyCarousel.Loaded += OnCarouselLoaded;
}

protected override void OnDisappearing()
{
    MyCarousel.PropertyChanged -= OnCarouselPropertyChanged;
    MyCarousel.Loaded -= OnCarouselLoaded;
}

private void OnCarouselPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
{
    if (e.PropertyName != nameof(PanCardView.CardsView.SelectedIndex))
    {
        return;
    }

    LoadCarouselViewIfNeeded();
}

private void OnCarouselLoaded(object sender, EventArgs e)
{
    LoadCarouselViewIfNeeded();
}

private void LoadCarouselViewIfNeeded()
{
    if (MyCarousel.CurrentView is Sharpnado.Tabs.ALazyView lazyView && !lazyView.IsLoaded)
    {
        lazyView.LoadView();
    }
}
```

**Comment by AndreiMisiukevich** [comment]
@DashTheDev maaan, you rock as always!

**Comment by AndreiMisiukevich** [comment]
Just wanna add, that @dima059 you can use `ItemAppeared` event instead of OnCarouselPropertyChanged

**Comment by AndreiMisiukevich** [comment]
And one more note (it's not your case because you are putting views directly to the carousel as a source).

If you used ItemTemplate, in your case, you would want to set `IsViewReusingEnabled = false` and probably `ShouldShareViewAmongSameItems = true`.

But again, it's not your case and code behind solution proposed by @DashTheDev should be enough

Closing it for now

**Comment by dima059** [comment]
Guys, you are the best! Thank you for such a quick response, you helped me a lot. And special thanks @AndreiMisiukevich for the CarouselView 🥇
